language: go
go: 
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

services:
  - neo4j

notificaitons:
  email:
    recipients:
      jason.mcvetta@gmail.com
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - httpie

before_script:
  - http -a neo4j:neo4j POST http://localhost:7474/user/neo4j/password password=foobar

env:
  global:
    - NEO4J_URL=http://neo4j:foobar@localhost:7474/db/data/

script:
  - go test -v
