language: go
services: neo4j
notificaitons:
  email:
    recipients:
      jason.mcvetta@gmail.com
    on_success: change
    on_failure: always
before_script:
  - go get -v github.com/bmizerany/assert
